// Generated by CoffeeScript 1.9.3
var add_random_layer, callback, cloudburst;

add_random_layer = function(json) {
  var addElement, cloudburstTileLayer, i, j, k, len, len1, len2, lyr, map, randomindex, ref, ref1, ref2, suplementary;
  cloudburstTileLayer = L.cloudburstTileLayer('http://localhost:6060', json, {
    maxZoom: 8,
    maxNativeZoom: 9,
    reuseTiles: true,
    detectRetina: true
  });
  randomindex = Math.floor(Math.random() * Object.keys(json.layers).length);
  cloudburstTileLayer.setLayer(Object.keys(json.layers)[randomindex]);
  suplementary = L.tileLayer('http://{s}.basemaps.cartocdn.com/dark_nolabels/{z}/{x}/{y}.png', {
    maxZoom: 9,
    reuseTiles: true,
    detectRetina: true
  });
  map = new L.Map('map', {
    layers: [suplementary, cloudburstTileLayer],
    center: new L.LatLng(-37.7772, 175.2756),
    zoom: 6,
    attributionControl: false
  });
  addElement = function(container_id, element, content) {
    var container, el;
    container = document.getElementById(container_id);
    el = document.createElement(element);
    el.innerHTML = '<a href="#">' + content + '</a>';
    return container.appendChild(el);
  };
  ref = cloudburstTileLayer.getLayers();
  for (i = 0, len = ref.length; i < len; i++) {
    lyr = ref[i];
    addElement('layers', 'li', lyr);
  }
  ref1 = cloudburstTileLayer.getInstances();
  for (j = 0, len1 = ref1.length; j < len1; j++) {
    lyr = ref1[j];
    addElement('instances', 'li', lyr);
  }
  ref2 = cloudburstTileLayer.getTindexes(true);
  for (k = 0, len2 = ref2.length; k < len2; k++) {
    lyr = ref2[k];
    addElement('indexes', 'li', lyr);
  }
  return setInterval(function() {
    return cloudburstTileLayer.forward(true);
  }, 5000);
};

cloudburst = new Cloudburst('http://localhost:6060');

callback = add_random_layer;

cloudburst.loadConfiguration(callback);
